import React from "react";
import PagesBanner from "../components/Layout/PagesBanner";
import Bookdemocard from "../components/Layout/Bookdemocard";
import Grid from "@mui/material/Grid";
import { styled } from "@mui/material/styles";
import Box from "@mui/material/Box";
import Paper from "@mui/material/Paper";
import { Typography } from "@mui/material";
import Card from "@mui/material/Card";
import CardMedia from "@mui/material/CardMedia";
import CardContent from "@mui/material/CardContent";

const Item = styled(Paper)(({ theme }) => ({
  backgroundColor: theme.palette.mode === "dark" ? "#1A2027" : "#fff",
  ...theme.typography.body2,
  padding: theme.spacing(1),
  textAlign: "justify",
  paddingTop: "30px",
  paddingLeft: "30px",
  paddingRight: "30px",
  color: theme.palette.text.secondary,
}));

const Mobileapps = () => {
  return (
    <div>
      <PagesBanner
        bgImg="https://png.pngtree.com/background/20210710/original/pngtree-blue-digital-technology-electronic-banner-picture-image_1033187.jpg"
        mainTitle="CUSTOM WEB APPLICATION DEVELOPMENT"
        subtext="Re-define your IT needs with highly reliable solutions for critical applications."
      />
      <Box
        sx={{
          flexGrow: 1,
          padding: { xs: "2px", md: "60px" },
          backgroundColor: "#F0F3F7",
        }}
      >
        <Grid container spacing={4}>
          <Grid item xs={12} md={8}>
            <Item>
              <Typography variant="h5" color="#3e4555">
                Hybrid Mobile App Development
              </Typography>
              <br />
              <Typography variant="p" fontSize={"18px"}>
                Mobile devices, especially Smartphones, are personal and
                intimate devices which in most of the cases are with the users
                24X7 and not more than 1 meter away. More than 50% of internet
                users access internet through their mobile phones. We help
                enterprises adopt best practices and processes for mobile
                applications. We build proof-of-concepts around emerging
                technologies and collaborate with enterprises to align specific
                to business needs. In the age of smart phones - Apple iPhone and
                Google Android, DGBITS offers wide range of mobility services
                and solutions. It goes beyond just the mobile apps development
                to Mobile First strategy for your business.
              </Typography>
              <br />
              <br />
              <Typography variant="p" fontSize={"18px"}>
                You may have an idea for the next Mobile app & we will help you
                transform your idea into reality. Whether your app is targeted
                to consumer market or enterprise, we have the expertise to build
                quality-rich Mobile apps at a competitive price for both Andriod
                & IOS.
              </Typography>
              <br />
              <br />
              <Typography variant="p" fontSize={"18px"}>
                Hybrid app development is the development of one single
                application on one codebase, that can run on multiple operating
                systems. Typical Hybrid Apps run across Windows, iOS and Android
                devices. The most interesting thing about the hybrid App
                development is the time and cost efficiency generated by using a
                single codebase. About 80 % of the codebase can be reused for
                other operating systems, while the other 20 % are usually
                specific to each operating system.
              </Typography>
              <br />
              <br />

              <Typography variant="p" fontSize={"18px"}>
                Notwithstanding that Hybrid Apps are developed on web
                technologies, they can provide similar UI/UX as native apps, and
                moreover have equal capabilities to work across several
                platforms. They allow developers to write only one code base
                that can be applied to all operating systems, which is very
                cost-effective.
              </Typography>
              <br />
              <br />
            </Item>
          </Grid>
          <Grid item xs={12} md={4}>
            {/* <ItemTwo> */}

            <Box
              sx={{
                display: "flex",
                flexDirection: "column",
                justifyContent: "center",
                alignItems: "center",
              }}
            >
              <Card sx={{ maxWidth: { xs: "95%", md: "345" } }}>
                <CardMedia
                  sx={{ height: 300 }}
                  image="https://dgbits.in/images/mobile-app.jpg"
                  title="green iguana"
                />
                <CardContent>
                  <Typography gutterBottom variant="h5" component="div">
                    How do Hybrid Apps work?
                  </Typography>
                  <Typography variant="body2" color="text.secondary">
                    As you can see from the name, hybrid apps are a mix of two
                    different applications - native apps and web apps. As a
                    rule, technologies such as CSS, HTML or JavaScript are used.
                    These can be combined with open source components of
                    frameworks like React Native or Flutter can be integrated
                    into a native application. These technologies allow hybrid
                    apps to run through each of the platforms‘ implemented
                    browser, which offers the possibility to be installed on
                    mobile apps and therefore implemented into the Play Store or
                    AppStore.
                  </Typography>
                  <br />
                </CardContent>
              </Card>
            </Box>

            {/* </ItemTwo> */}
          </Grid>
        </Grid>
      </Box>
      <Bookdemocard maintext="Mobility solutions to Increase productivity and efficiency." />
    </div>
  );
};

export default Mobileapps;
